docker_agent: http://47.244.185.243:2001
services:
  dubbo-admin:
    image: dubbo-admin
    container: dubbo-admin
    ports:
      - '8080:4321'
    network: bridge
    volumes:
      - '/data/server/dubbo-admin/logs:/logs'
    java_opts: "-Xms512m -Xmx512m"

  dubbo-monitor:
    image: dubbo-monitor
    container: dubbo-monitor
    ports:
      - '8080:4322'
    network: bridge
    volumes:
      - '/data/server/dubbo-monitor/logs:/logs'
    java_opts: "-Xms512m -Xmx512m"

  rocketmq-console-ng:
    image: rocketmq-console-ng
    container: rocketmq-console-ng
    ports:
      - '8080:4323'
    network: bridge
    volumes:
      - '/data/server/rocketmq-console-ng/logs:/logs'
    environment:
      - 'rocketmq.config.namesrvAddr=192.168.0.144:9876;192.168.0.145:9876'
    java_opts: '-Xms512m -Xmx512m -Drocketmq.config.namesrvAddr=192.168.0.144:9876;192.168.0.145:9876'