repository: registry-vpc.cn-hongkong.aliyuncs.com/lovanow_beta
docker_agent: http://47.75.72.87:7000
services:
  elasticsearch:
    image: elasticsearch:5.4.3-ali
    container: elasticsearch
    hosts:
      - 172.16.0.209
    network: host
    volumes:
      - '/data/server/elasticsearch/data:/usr/share/elasticsearch/data'
      - '/data/server/elasticsearch/logs:/usr/share/elasticsearch/logs'
      - '/data/server/elasticsearch/backup:/usr/share/elasticsearch/backup'
    ulimits:
      - 
        name: nofile
        softLimit: 5000
        hardLimit: 6000
    environment:
      - 'ES_JAVA_OPTS="-Xms512m -Xmx512m"'