docker_agent: http://47.75.144.156:2000
compose_server: fastdfs
services:
  fdfs_tracker:
    image: fastdfs:v2
    container: fdfs-tracker
    hosts:
      - 192.168.0.140
      - 192.168.0.142
      - 192.168.0.143
    network: host
    volumes:
      - '/data/server/fastdfs:/data'
    command: [/start.sh,tracker]
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
  fdfs_storage:
    image: fastdfs:v2
    container: fdfs-storage
    hosts:
      - 192.168.0.140
      - 192.168.0.142
      - 192.168.0.143
    network: host
    volumes:
      - '/data/server/fastdfs:/data'
    command: [/start.sh, storage]
    environment:
      - 'TRACKER_SERVER=192.168.0.140:22122,192.168.0.142:22122,192.168.0.143:22122'
      - 'GROUP_NAME=group1'
      - 'BIND_ADDR=$HOST_IP'
      - 'WEB_PORT=8000'
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}

