docker_agent: http://47.75.144.156:2000
services:
  filebeat_logdown:
    image: filebeat_logstash:5.4.3-20190520
    container: filebeat-logdown
    network: bridge
    volumes:
      - '/data/server/filebeat_downtrank/data:/data'
      - '/data/server/filebeat_downtrank/logs:/logs'
      - '/data/server/logs/logs-downtank:/applogs'
    environment:
      - 'LOGSTASH_HOSTS=192.168.0.155:5044'
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
  filebeat-kfk: 
    image: filebeat_kafka:5.4.3-20190520
    container: filebeat-kfk
    network: bridge
    volumes:
      - '/data/server/filebeat_kfk/data:/data'
      - '/data/server/filebeat_kfk/logs:/logs'
      - '/data/server/logs/oauth:/applogs'
    environment:
      - 'KAFKA_HOSTS=192.168.0.154:9092'
      - 'KAFKA_TOPIC=nowslv'
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
