docker_agent: http://47.244.185.243:2001
services:
  kafka:
    image: kafka:2.11-1.1.0
    container: kafka-2.11-1.1.0
    network: host
    volumes:
      - '/data/server/kafka/data:/data/kafka-logs'
      - '/data/server/kafka/logs:/usr/bin/kafka/logs'
    environment:
      - 'KAFKA_HEAP_OPTS=-Xms1024m -Xmx2014m'
      - 'zkServrs=192.168.0.240:2181,192.168.0.142:2181,102.168.0.143:2181'
      - 'hostport=$HOST_IP:9092'
      - 'id=0'
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}