repository: registry-vpc.cn-hongkong.aliyuncs.com/lovanow_beta
docker_agent: http://47.75.72.87:7000
services:
  kafka:
    image: kafka:2.11-1.1.0
    container: kafka-2.11-1.1.0
    hosts:
      - 172.16.0.209
    ports:
      - '9092:9092'
    network: bridge
    volumes:
      - '/data/server/kafka/data:/data'
      - '/data/server/kafka/logs:/logs'
    environment:
      - 'KAFKA_HEAP_OPTS="-Xms512m -Xmx512m"'
      - 'zkServrs=172.16.0.200:2181,172.16.0.201:2181,172.16.0.202:2181'
      - 'hostport=172.16.0.209:9092'
      - 'id=0'
      - 'logDirs=/data'
      - 'LOG_DIR=/logs'
    ulimits:
      - 
        name: nofile
        softLimit: 5000
        hardLimit: 6000