repository: registry-vpc.cn-hongkong.aliyuncs.com/lovanow_beta
docker_agent: http://47.75.72.87:7000
services:
  logcollecter:
    image: logcollecter:v1
    container: ogcollecter
    hosts:
      - 172.16.0.207
    network: bridge
    volumes:
      - '/data/ServerLogs:/logs'
    environment:
      - 'KFKHOSTS=172.16.0.209:9092'
      - 'TOPIC_PREFIX=beatlovanowlog_'
      - 'LOGPATH=/logs'
    ulimits:
      - {"name": "nofile","softLimit": 5000, "hardLimit": 6000}
  filebeat-kfk:
    image: filebeat-kfk-alpine:6.4.3
    container: filebeat-kfk
    hosts:
      - 172.16.0.207
      - 172.16.0.210
      - 172.16.0.211
    network: host
    volumes:
      - '/data/server/filebeat-kfk:/filebeat'
      - '/data/server/logs:/applogs'
    environment:
      - 'monitor_path=/applogs/*/*.log'
      - 'kafaka_host=172.16.0.209:9092'
      - 'kafaka_topic=beatlovanowlog_$HOSTNAME'
      - 'beatdata_path=/filebeat'
    ulimits:
      - {"name": "nofile","softLimit": 5000, "hardLimit": 6000}
