docker_agent: http://47.244.185.243:2001
zkserver: &zkserver 'ZK_SERVER=192.168.0.140:2181,192.168.0.142:2181,192.168.0.143:2181'
sparkmaster: &sparkmaster 'SPARK_MASTER=spark://192.168.0.156:7077'
kafka: &kafka 'KAFKA_URL=192.168.0.154:9092'
eshost: &eshost 'ES_HOST=192.168.0.154'
esport: &esport 'ES_PORT=9200'
duration: &duration 'SPARK_DURATION=10'
services:
  facerpcsrv:
    image: facerpcsrv
    ports:
      - '9000:9084'
    network: bridge
    volumes:
      - '/data/server/face/model:/model'
      - '/data/server/face/facerpcsrv:/logs'
    environment:
      - *zkserver
      - 'domainMap=storage1.sensenow.com:lovabeta.oss-cn-hongkong-internal.aliyuncs.com'
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
  recmdrpcsvr:
    image: recmdrpcsvr
    ports:
      - '9000:9085'
    network: bridge
    volumes:
      - '/data/server/logs/recmdrpcsvr:/logs'
    environment:
      - *zkserver
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
  recmdcallrate:
    image: recmdspark
    network: host
    volumes:
      - /data/server/recmdcallrate/logs:/var/log/charles/recmd
    environment:
      - *sparkmaster
      - 'MAIN_CLASS=com.jwaoo.recmd.CallRateFactor'
      - *kafka
      - *eshost
      - *esport
      - *duration
  recmdrecharge:
    image: recmdspark
    network: host
    volumes:
      - /data/server/recmdrecharge/logs:/var/log/charles/recmd
    environment:
      - *sparkmaster
      - 'MAIN_CLASS=com.jwaoo.recmd.ChargeFactor'
      - *kafka
      - *eshost
      - *esport
      - *duration