docker_agent: http://47.244.185.243:2001
services:
  facerpcsrv:
    image: facerpcsrv
    ports:
      - '9000:9084'
    network: bridge
    volumes:
      - '/data/server/face/model:/model'
      - '/data/server/face/facerpcsrv:/logs'
    environment:
      - 'ZK_SERVER=192.168.0.140:2181,192.168.0.142:2181,192.168.0.143:2181'
      - 'domainMap=storage1.sensenow.com:lovabeta.oss-cn-hongkong-internal.aliyuncs.com'
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
  recmdrpcsvr:
    image: recmdrpcsvr
    ports:
      - '9000:9085'
    network: bridge
    volumes:
      - '/data/server/logs/recmdrpcsvr:/logs'
    environment:
      - 'ZK_SERVER=192.168.0.140:2181,192.168.0.142:2181,192.168.0.143:2181'
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
  recmdcallrate:
    image: recmdspark
    network: bridge
    volumes:
      - /data/server/recmdcallrate/logs:/var/log/charles/recmd
    environment:
      - 'SPARK_MASTER=spark://192.168.0.156:7077'
      - 'MAIN_CLASS=com.jwaoo.recmd.CallRateFactor'
      - 'KAFKA_URL=192.168.0.154:9092'
      - 'ES_HOST=192.168.0.154'
      - 'ES_PORT=9200'
      - 'SPARK_DURATION=10'
  recmdrecharge:
    image: recmdspark
    network: bridge
    volumes:
      - /data/server/recmdrecharge/logs:/var/log/charles/recmd
    environment:
      - 'SPARK_MASTER=spark://192.168.0.156:7077'
      - 'MAIN_CLASS=com.jwaoo.recmd.ChargeFactor'
      - 'KAFKA_URL=192.168.0.154:9092'
      - 'ES_HOST=192.168.0.154'
      - 'ES_PORT=9200'
      - 'SPARK_DURATION=10'