docker_agent: http://47.75.144.156:2000
compose_server: rocketmq
services:
  mq-namesrv:
    image: rocketmq-4.2.0:v2
    container: mq-namesrv
    hosts:
      - 192.168.0.144
      - 192.168.0.145
    network: host
    volumes:
      - /data/server/rocketmq:/data
    command: [/start.sh]
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
    environment: 
      - role=namesrv
  mq-broker-a:
    image: rocketmq-4.2.0:v2
    container: mq-broker-a
    hosts:
      - 192.168.0.144
    network: host
    volumes:
      - /data/server/rocketmq:/data
    command: [/start.sh]
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
    environment: 
      - role=master_noslave
      - cname=lovanow_beta
      - brokerName=broker-a
      - brokerip=$HOST_IP
      - namesrvAddr=192.168.0.144:9876;192.168.0.145:9876
  mq-broker-b:
    image: rocketmq-4.2.0:v2
    container: mq-broker-b
    hosts:
      - 192.168.0.145
    network: host
    volumes:
      - /data/server/rocketmq:/data
    command: [/start.sh]
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
    environment: 
      - role=master_noslave
      - cname=lovanow_beta
      - brokerName=broker-b
      - brokerip=$HOST_IP
      - namesrvAddr=192.168.0.144:9876;192.168.0.145:9876