repository: registry-vpc.cn-hongkong.aliyuncs.com/lovanow_beta
docker_agent: http://47.75.72.87:7000
compose_server: rocketmq
services:
  mq-namesrv:
    image: rocketmq:v2
    container: mq-namesrv
    hosts:
      - 172.16.0.200
      - 172.16.0.201
    network: host
    volumes:
      - /data/server/rocketmq:/data
    command: /start.sh
    ulimits:
      - {"name": "nofile","softLimit": 10000, "hardLimit": 12000}
    environment: 
      - role=namesrv
  mq-broker-a:
    image: rocketmq:v2
    container: mq-broker-a
    hosts:
      - 172.16.0.200
    network: host
    volumes:
      - /data/server/rocketmq:/data
    command: /start.sh
    ulimits:
      - {"name": "nofile","softLimit": 10000, "hardLimit": 12000}
    environment: 
      - role=master_noslave
      - cname=lovanow_beta
      - brokerName=broker-a
      - brokerip=$HOST_IP
      - namesrvAddr=172.16.0.201:9876;172.16.0.200:9876
  mq-broker-b:
    image: rocketmq:v2
    container: mq-broker-b
    hosts:
      - 172.16.0.201
    network: host
    volumes:
      - /data/server/rocketmq:/data
    command: /start.sh
    ulimits:
      - {"name": "nofile","softLimit": 10000, "hardLimit": 12000}
    environment: 
      - role=master_noslave
      - cname=lovanow_beta
      - brokerName=broker-b
      - brokerip=$HOST_IP
      - namesrvAddr=172.16.0.201:9876;172.16.0.200:9876