repository: registry-vpc.cn-hongkong.aliyuncs.com/lovanow_beta
docker_agent: http://47.75.72.87:7000
services:
  im_server:
    image: im_server
    hosts:
      - 172.16.0.210
    ports:
      - '8080:9087'
      - '8090:9088'
    network: bridge
    volumes:
      - '/data/server/logs/im_server:/logs'
    environment:
      - 'ZK_SERVER=172.16.0.200:2181,172.16.0.201:2181,172.16.0.202:2181'
      - 'MONGO_SERVER=mongodb://jwaoo_im:123456@s-j6cfc4998e52dd44.mongodb.rds.aliyuncs.com:3717,s-j6c1b81867724ca4.mongodb.rds.aliyuncs.com:3717/jwaoo_im'
      - 'REDIS_SERVER=r-j6c1a2df0e7ab504.redis.rds.aliyuncs.com:6379'
      - 'MqNameServer=172.16.0.200:9876;172.16.0.201:9876'
      - 'ACCOUNT=http://172.16.0.202:8080'
      - 'PUSH=http://172.16.0.202:8091'
      - 'CLIENTID=5c63f0b2c74d673ea5700180'
      - 'IM_ROLE=SERVER'
    ulimits:
      - 
        name: nofile
        softLimit: 5000
        hardLimit: 6000
  im_router:
    image: im_router
    hosts:
      - 172.16.0.210
    ports:
      - '8080:9086'
    network: bridge
    volume:
      - '/data/server/logs/im_router:/logs'
    environment:
      - 'ZK_SERVER=172.16.0.200:2181,172.16.0.201:2181,172.16.0.202:2181'
      - 'MONGO_SERVER=mongodb://jwaoo_im:123456@s-j6cfc4998e52dd44.mongodb.rds.aliyuncs.com:3717,s-j6c1b81867724ca4.mongodb.rds.aliyuncs.com:3717/jwaoo_im'
      - 'REDIS_SERVER=r-j6c1a2df0e7ab504.redis.rds.aliyuncs.com:6379'
      - 'MqNameServer=172.16.0.200:9876;172.16.0.201:9876'
      - 'ACCOUNT=http://172.16.0.202:8080'
      - 'PUSH=http://172.16.0.202:8091'
      - 'CLIENTID=5c63f0b2c74d673ea5700180'
      - 'IM_ROLE=ROUTER'
    ulimits:
      - 
        name: nofile
        softLimit: 5000
        hardLimit: 6000