docker_agent: http://47.244.185.243:2001
services:
  apprtc:
    image: apprtc
    ports:
      - '8080:9080'
    network: bridge
    volumes:
      - '/data/server/logs/apprtc:/logs'
    environment:
      - 'ZK_SERVER=192.168.0.140:2181,192.168.0.142:2181,192.168.0.143:2181'
      - 'EXT_PUB_IP=beta3.sensenow.com'
      - 'RTC_TLS=true'
      - 'COLLIDER_HOST=beta3.sensenow.com'
      - 'COLLIDER_PORT=80'
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
  collider:
    image: collider
    ports:
      - '8080:9081'
    network: bridge
    volumes:
      - '/data/server/logs/collider:/logs'
    environment:
      - 'ZK_SERVER=192.168.0.140:2181,192.168.0.142:2181,192.168.0.143:2181'
      - 'COLLIDER_HOST=beta3.sensenow.com'
      - 'COLLIDER_PORT=80'
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}