docker_agent: http://47.244.185.243:2001
compose_server: zk
services:
  spark:
    image: spark:2.1.2-hadoop2.4
    container: spark
    network: host
    volumes:
      - /data/server/spark/logs:/usr/bin/spark/logs
      - /data/server/spark/recmd:/var/log/charles/recmd
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
    environment: 
      - mode=all
      - MEMORY_SIZE=3g
      - DRIVER_MEM=1g
      - CPU_CORES=1