docker_agent: http://47.75.144.156:2000
compose_server: zookeeper
services:
  zkserver0:
    image: zookeeper:v1
    container: zk-cluster.0
    hosts:
      - 192.168.0.140
    network: host
    volumes:
      - /data/server/zookeeper:/data
    command: [/start.sh]
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
    extra_hosts:
      - zkserver1:192.168.0.140
      - zkserver2:192.168.0.142
      - zkserver3:192.168.0.143
    environment: 
      - myid=0
      - zkip=$HOST_IP
  zkserver1:
    image: zookeeper:v1
    container: zk-cluster.1
    hosts:
      - 192.168.0.142
    network: host
    volumes:
      - /data/server/zookeeper:/data
    command: [/start.sh]
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
    extra_hosts:
      - zkserver1:192.168.0.140
      - zkserver2:192.168.0.142
      - zkserver3:192.168.0.143
    environment: 
      - myid=1
      - zkip=$HOST_IP
  zkserver2:
    image: zookeeper:v1
    container: zk-cluster.2
    hosts:
      - 192.168.0.143
    network: host
    volumes:
      - /data/server/zookeeper:/data
    command: [/start.sh]
    ulimits:
      - {"name": "nofile","soft": 10000, "hard": 12000}
    extra_hosts:
      - zkserver1:192.168.0.140
      - zkserver2:192.168.0.142
      - zkserver3:192.168.0.143
    environment: 
      - myid=2
      - zkip=$HOST_IP
